id: A424381BE
title: Prayer to Machik Labdrön
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:43:21.395628
  last_modified_at: 2022-03-01 00:43:21.395633
